version: '3.0'

services:
  server: 
    container_name: "bookservice-server"
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - ./server:/server
      - server-node-modules:/server/node_modules
    depends_on:
      - database

  database:
    container_name: "bookservice-db"
    build: 
      context: ./database
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - database:/var/lib/post
    ports:
      - "5432:5432"
      
  

volumes:
  server-node-modules : 
    name : "server-node-modules"
  database : 
    name : "database"
