services:
  server: 
    container_name: "bookservice-server"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    container_name: "bookservice-db"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: